# -*- coding: utf-8 -*-
"""Trendpulse_Task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PtXj9X5gZwXVh-46Csj6txlynicDqUwE
"""

import requests
import time
import json
import os
from datetime import datetime

TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

headers = {
    "User-Agent": "TrendPulse/1.0"
}

categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

def get_top_story_ids():
    try:
        response = requests.get(TOP_STORIES_URL, headers=headers)
        return response.json()[:500]
    except:
        print("Error fetching top stories")
        return []

def get_story(story_id):
    try:
        url = ITEM_URL.format(story_id)
        response = requests.get(url, headers=headers)
        return response.json()
    except:
        print(f"Error fetching story {story_id}")
        return None

def categorize(title):
    title = title.lower()

    for category, keywords in categories.items():
        for keyword in keywords:
            if keyword in title:
                return category
    return None

story_ids = get_top_story_ids()

collected_stories = []
category_count = {cat: 0 for cat in categories}

for story_id in story_ids:
    story = get_story(story_id)

    if not story or "title" not in story:
        continue

    category = categorize(story["title"])

    if category and category_count[category] < 25:

        data = {
            "post_id": story.get("id"),
            "title": story.get("title"),
            "category": category,
            "score": story.get("score", 0),
            "num_comments": story.get("descendants", 0),
            "author": story.get("by"),
            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        collected_stories.append(data)
        category_count[category] += 1

    # sleep after category complete
    if category and category_count[category] == 25:
        print(f"{category} completed... waiting")
        time.sleep(2)

    if all(count >= 25 for count in category_count.values()):
        break

import os
import json

# Create data folder
if not os.path.exists("data"):
    os.makedirs("data")

filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

with open(filename, "w") as f:
    json.dump(collected_stories, f, indent=4)

print(f"Collected {len(collected_stories)} stories. Saved to {filename}")

"""# New Section"""